### PR TITLE
Feature: Add JDK11 on RHEL8 platforms

### PR DESCRIPTION
**Pull request by rmarting**
Updated JBoss Common role to cover the following tasks:

- Install JDK 8 on RHEL 7 platforms
- Install JDK 11 on RHEL 8 platforms
- Install PIP dependencies always (are used in other JBoss Roles)
- Update to use latest Ansible 2.9 version

### CODE REVIEW

**Comment by rmarting** [comment]
It seems that molecule test are not working successfully. I have not experience with molecule and I am trying to test in my local environment:

- Fedora 31
- Python 3.7.6
- pip 19.1.1

Who could update the molecule test to pass it? Thanks!

**Comment by davgordo** [comment]
@rmarting can you merge this PR to your fork? https://github.com/rmarting/ansible-role-jboss-common/pull/1

That should be able to get your PR to pass the CI checks.

**Review by sabre1041 — CHANGES_REQUESTED** [review]
Looks good. A few areas of discussion:

* `rhsm_repositories` provide defaults for RHEL7. Can we provide the same for RHEL8

**Comment by sabre1041** [comment]
@davgordo After a second review, I updated my comment to seek the list of repositories that should be enabled for RHEL8

**Pull request closed without merging**
